# Generated by Django 4.2.30 on 2026-04-27 09:17

from django.db import migrations, models
import resume.models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0002_skill_language_experience_education_certification_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to=resume.models.resume_upload_path
            ),
        ),
    ]
